### PR TITLE
Fix #333 Bug: app multiplying on the Apps page

### LINKED ISSUE #333: Bug: app multiplying on the Apps page
On the Apps page, the app “Mast” multiplies indefinitely when changing tabs:

https://user-images.githubusercontent.com/923008/228224975-64d5e9e1-210f-4181-93a2-ec86cd29ab52.mp4

### PR DESCRIPTION
**Pull request by cheeaun**
Possible fix for the duplicated app on the Apps page, due to duplicated `key`. Adding `name` here, assuming that it'll be unique enough 🤞

### CODE REVIEW

File: components/AppCard.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ export type AppCardProps = {
 export const AppCard = ({ name, icon, url, paid }) => {
   return (
     <a
-      key={url}
+      key={url + name}
```
Comment (ClearlyClaire) [inline components/AppCard.tsx:18]: I think the following should be more in line with the rest of the codebase regarding string interpolation, also makes it less likely for the start of the name to mess with the end of the URL:

```suggestion
      key={`${url} ${name}`}
```

**Review by ClearlyClaire — CHANGES_REQUESTED** [review]
Oh right, this is caused by Mast appearing with the same URL (but a different name) under both `ios` and `desktop`.

Given that the app list is static, I think a more robust solution would be to (programmatically) give them unique keys such as `ios-0`, `ios-1`, `desktop-0`, …

But your solution sounds fine with at least the current data.

**Review by ClearlyClaire — APPROVED** [review]
